-- Migration 20260902203400: seed the reviewed high-confidence market census
-- as governed proposals only.
--
-- This migration creates no revenue market, locality, listing membership,
-- source subscription, event, job, or external side effect. Every row remains
-- in needs_review with no resolved market. Counts are aggregate PriceLabs
-- source rows, not unique properties, and therefore cannot activate a market
-- or assign a listing without a separate reviewed migration.

WITH proposal_seed (
  state_code,
  proposed_slug,
  proposed_name,
  proposed_market_kind,
  locality_names,
  locality_slugs,
  source_row_count,
  confidence_score,
  exception_codes,
  rationale
) AS (
  VALUES
    ('TN', 'smokies-tn', 'Smoky Mountains', 'cabin',
      ARRAY['Gatlinburg', 'Sevierville', 'Pigeon Forge', 'Pittman Center']::TEXT[],
      ARRAY['gatlinburg', 'sevierville', 'pigeon-forge', 'pittman-center']::TEXT[],
      48, 0.90::NUMERIC,
      ARRAY['existing_market_merge_review', 'sevierville_state_conflict', 'hub_market_coverage_mismatch', 'exclude_knoxville_and_nashville']::TEXT[],
      'Review the four-locality Smokies definition, merge it into the existing market, and reconcile source-row and Hub membership counts.'),
    ('TN', 'knoxville-tn', 'Knoxville', 'urban',
      ARRAY['Knoxville']::TEXT[], ARRAY['knoxville']::TEXT[],
      1, 0.90::NUMERIC,
      ARRAY['proximity_chain_conflict_with_smokies', 'new_market_review_required']::TEXT[],
      'Create a distinct Knoxville market only after review; radius clustering must not merge it into the Smoky Mountains market.'),
    ('TN', 'nashville-tn', 'Nashville', 'urban',
      ARRAY['Nashville']::TEXT[], ARRAY['nashville']::TEXT[],
      1, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review a one-listing Nashville market instead of forcing the listing into an unrelated Tennessee market.'),
    ('SC', 'myrtle-beach-sc', 'Myrtle Beach / Grand Strand', 'coastal',
      ARRAY['North Myrtle Beach', 'Myrtle Beach']::TEXT[],
      ARRAY['north-myrtle-beach', 'myrtle-beach']::TEXT[],
      17, 0.90::NUMERIC,
      ARRAY['existing_market_merge_review', 'pricelabs_hub_count_reconciliation']::TEXT[],
      'Review both Grand Strand localities and merge the proposal into the existing Myrtle Beach market after identity reconciliation.'),
    ('PA', 'poconos-pa', 'Poconos', 'cabin',
      ARRAY['Albrightsville', 'East Stroudsburg', 'Tobyhanna', 'Blakeslee', 'Lake Harmony']::TEXT[],
      ARRAY['albrightsville', 'east-stroudsburg', 'tobyhanna', 'blakeslee', 'lake-harmony']::TEXT[],
      9, 0.90::NUMERIC, ARRAY[]::TEXT[],
      'Review the five-locality Poconos destination cluster as one primary revenue market.'),
    ('WI', 'lake-geneva-wi', 'Lake Geneva', 'destination',
      ARRAY['Lake Geneva', 'Fontana-on-Geneva Lake']::TEXT[],
      ARRAY['lake-geneva', 'fontana-on-geneva-lake']::TEXT[],
      9, 0.90::NUMERIC, ARRAY[]::TEXT[],
      'Review Lake Geneva and Fontana-on-Geneva Lake as one destination market.'),
    ('CA', 'north-lake-tahoe-ca', 'North Lake Tahoe', 'destination',
      ARRAY['Tahoe Vista', 'Carnelian Bay', 'Homewood', 'Kings Beach', 'Tahoe City']::TEXT[],
      ARRAY['tahoe-vista', 'carnelian-bay', 'homewood', 'kings-beach', 'tahoe-city']::TEXT[],
      6, 0.90::NUMERIC,
      ARRAY['cross_state_influence_boundary_review']::TEXT[],
      'Review the California North Lake Tahoe localities and any secondary Nevada demand influence without creating cross-state membership automatically.'),
    ('TX', 'dallas-fort-worth-tx', 'Dallas–Fort Worth', 'urban',
      ARRAY['Dallas', 'Fort Worth', 'Arlington', 'Grand Prairie', 'Irving']::TEXT[],
      ARRAY['dallas', 'fort-worth', 'arlington', 'grand-prairie', 'irving']::TEXT[],
      6, 0.90::NUMERIC, ARRAY[]::TEXT[],
      'Review the five-city Dallas–Fort Worth metro as one primary market with canonical localities.'),
    ('MD', 'deep-creek-lake-md', 'Deep Creek Lake', 'cabin',
      ARRAY['McHenry', 'Oakland']::TEXT[], ARRAY['mchenry', 'oakland']::TEXT[],
      2, 0.90::NUMERIC, ARRAY[]::TEXT[],
      'Review McHenry and Oakland as the Deep Creek Lake destination market.'),
    ('SD', 'black-hills-sd', 'Black Hills', 'destination',
      ARRAY['Keystone', 'Custer']::TEXT[], ARRAY['keystone', 'custer']::TEXT[],
      3, 0.90::NUMERIC, ARRAY[]::TEXT[],
      'Review Keystone and Custer as one Black Hills destination market.'),
    ('OH', 'cincinnati-oh', 'Cincinnati', 'urban',
      ARRAY['Cincinnati', 'Loveland']::TEXT[], ARRAY['cincinnati', 'loveland']::TEXT[],
      4, 0.90::NUMERIC, ARRAY[]::TEXT[],
      'Review Cincinnati and Loveland as one Cincinnati primary market.'),
    ('MT', 'glacier-whitefish-mt', 'Glacier / Whitefish', 'destination',
      ARRAY['Columbia Falls', 'Whitefish']::TEXT[], ARRAY['columbia-falls', 'whitefish']::TEXT[],
      2, 0.90::NUMERIC, ARRAY[]::TEXT[],
      'Review Columbia Falls and Whitefish as one Glacier-area destination market.'),
    ('NC', 'asheville-area-nc', 'Asheville area', 'mixed',
      ARRAY['Fairview', 'Avery Creek']::TEXT[], ARRAY['fairview', 'avery-creek']::TEXT[],
      3, 0.90::NUMERIC,
      ARRAY['keep_lake_lure_separate']::TEXT[],
      'Review Fairview and Avery Creek as the Asheville-area market while keeping Lake Lure separate.'),
    ('NC', 'lake-lure-nc', 'Lake Lure', 'destination',
      ARRAY['Lake Lure']::TEXT[], ARRAY['lake-lure']::TEXT[],
      2, 0.95::NUMERIC,
      ARRAY['keep_asheville_primary_separate']::TEXT[],
      'Review Lake Lure as its own primary market with Asheville retained only as a possible secondary influence.'),
    ('WA', 'olympic-peninsula-wa', 'Olympic Peninsula', 'destination',
      ARRAY['Forks']::TEXT[], ARRAY['forks']::TEXT[],
      9, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review Forks as the initial canonical locality for an Olympic Peninsula destination market.'),
    ('WA', 'mount-rainier-north-wa', 'Mount Rainier North', 'destination',
      ARRAY['Enumclaw']::TEXT[], ARRAY['enumclaw']::TEXT[],
      5, 0.90::NUMERIC,
      ARRAY['shared_secondary_influence_with_mount_rainier_south']::TEXT[],
      'Review Enumclaw as the northern Mount Rainier primary market and model shared demand only as a secondary influence.'),
    ('WA', 'mount-rainier-south-wa', 'Mount Rainier South', 'destination',
      ARRAY['Ashford']::TEXT[], ARRAY['ashford']::TEXT[],
      2, 0.90::NUMERIC,
      ARRAY['shared_secondary_influence_with_mount_rainier_north']::TEXT[],
      'Review Ashford as the southern Mount Rainier primary market and model shared demand only as a secondary influence.'),
    ('UT', 'park-city-ut', 'Park City', 'destination',
      ARRAY['Park City']::TEXT[], ARRAY['park-city']::TEXT[],
      3, 0.95::NUMERIC,
      ARRAY['existing_market_merge_review', 'keep_salt_lake_city_primary_separate']::TEXT[],
      'Review and merge the canonical Park City locality into the existing market while keeping Salt Lake City separate.'),
    ('UT', 'salt-lake-city-ut', 'Salt Lake City', 'urban',
      ARRAY['Salt Lake City']::TEXT[], ARRAY['salt-lake-city']::TEXT[],
      1, 0.95::NUMERIC,
      ARRAY['keep_park_city_primary_separate']::TEXT[],
      'Review a separate Salt Lake City primary market; Park City may receive only a separately reviewed secondary influence.'),
    ('NJ', 'atlantic-city-coast-nj', 'Atlantic City coast', 'coastal',
      ARRAY['Brigantine']::TEXT[], ARRAY['brigantine']::TEXT[],
      6, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review Brigantine as the initial canonical locality for the Atlantic City coastal market.'),
    ('NJ', 'newark-nyc-influence-nj', 'Newark / NYC influence', 'urban',
      ARRAY['Harrison']::TEXT[], ARRAY['harrison']::TEXT[],
      3, 0.90::NUMERIC,
      ARRAY['cross_state_demand_influence_review']::TEXT[],
      'Review Harrison as a New Jersey primary market while treating New York City only as a possible secondary demand influence.'),
    ('CA', 'orange-county-coast-ca', 'Orange County coast', 'coastal',
      ARRAY['Newport Beach']::TEXT[], ARRAY['newport-beach']::TEXT[],
      8, 0.95::NUMERIC,
      ARRAY['keep_anaheim_santa_ana_primary_separate']::TEXT[],
      'Review Newport Beach as the Orange County coastal primary market, separate from Anaheim and Santa Ana.'),
    ('CA', 'anaheim-santa-ana-ca', 'Anaheim / Santa Ana', 'urban',
      ARRAY['Anaheim', 'Santa Ana']::TEXT[], ARRAY['anaheim', 'santa-ana']::TEXT[],
      2, 0.90::NUMERIC,
      ARRAY['keep_orange_county_coast_primary_separate']::TEXT[],
      'Review Anaheim and Santa Ana as an urban primary market, separate from the Newport Beach coastal market.'),
    ('CO', 'denver-metro-co', 'Denver metro', 'urban',
      ARRAY['Denver', 'Arvada']::TEXT[], ARRAY['denver', 'arvada']::TEXT[],
      5, 0.90::NUMERIC,
      ARRAY['keep_boulder_primary_separate']::TEXT[],
      'Review Denver and Arvada as the Denver metro primary market while keeping Boulder separate.'),
    ('CO', 'boulder-co', 'Boulder', 'urban',
      ARRAY['Boulder']::TEXT[], ARRAY['boulder']::TEXT[],
      1, 0.95::NUMERIC,
      ARRAY['keep_denver_primary_separate']::TEXT[],
      'Review a one-listing Boulder primary market with Denver retained only as a possible secondary influence.'),
    ('AZ', 'tucson-az', 'Tucson', 'urban',
      ARRAY['Tucson']::TEXT[], ARRAY['tucson']::TEXT[],
      10, 0.95::NUMERIC,
      ARRAY['existing_market_merge_review', 'pricelabs_hub_count_reconciliation']::TEXT[],
      'Review the canonical Tucson locality and merge it into the existing market after reconciling PriceLabs and Hub counts.'),
    ('CA', 'san-diego-ca', 'San Diego', 'coastal',
      ARRAY['San Diego']::TEXT[], ARRAY['san-diego']::TEXT[],
      5, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review the same-city San Diego cluster as a primary coastal market.'),
    ('CO', 'glenwood-springs-co', 'Glenwood Springs', 'destination',
      ARRAY['Glenwood Springs']::TEXT[], ARRAY['glenwood-springs']::TEXT[],
      5, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review the same-city Glenwood Springs cluster as a destination market.'),
    ('WI', 'milwaukee-wi', 'Milwaukee', 'urban',
      ARRAY['Milwaukee']::TEXT[], ARRAY['milwaukee']::TEXT[],
      5, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review the same-city Milwaukee cluster as a primary urban market.'),
    ('TX', 'austin-tx', 'Austin', 'urban',
      ARRAY['Austin']::TEXT[], ARRAY['austin']::TEXT[],
      4, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review the same-city Austin cluster as a primary urban market.'),
    ('NE', 'omaha-ne', 'Omaha', 'urban',
      ARRAY['Omaha']::TEXT[], ARRAY['omaha']::TEXT[],
      4, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review the same-city Omaha cluster as a primary urban market.'),
    ('CA', 'lodi-ca', 'Lodi', 'mixed',
      ARRAY['Lodi']::TEXT[], ARRAY['lodi']::TEXT[],
      4, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review the same-city Lodi cluster as a primary market.'),
    ('FL', 'gainesville-fl', 'Gainesville', 'urban',
      ARRAY['Gainesville']::TEXT[], ARRAY['gainesville']::TEXT[],
      3, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review the same-city Gainesville cluster as a primary urban market.'),
    ('AZ', 'sedona-az', 'Sedona', 'destination',
      ARRAY['Sedona']::TEXT[], ARRAY['sedona']::TEXT[],
      3, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review the same-city Sedona cluster as a primary destination market.'),
    ('AZ', 'page-az', 'Page', 'destination',
      ARRAY['Page']::TEXT[], ARRAY['page']::TEXT[],
      3, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review the same-city Page cluster as a primary destination market.'),
    ('TX', 'galveston-tx', 'Galveston', 'coastal',
      ARRAY['Galveston']::TEXT[], ARRAY['galveston']::TEXT[],
      3, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review the same-city Galveston cluster as a primary coastal market.'),
    ('NC', 'charlotte-nc', 'Charlotte', 'urban',
      ARRAY['Charlotte']::TEXT[], ARRAY['charlotte']::TEXT[],
      3, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review the same-city Charlotte cluster as a primary urban market.'),
    ('MT', 'livingston-mt', 'Livingston', 'destination',
      ARRAY['Livingston']::TEXT[], ARRAY['livingston']::TEXT[],
      3, 0.95::NUMERIC, ARRAY[]::TEXT[],
      'Review the same-city Livingston cluster as a primary destination market.')
),
normalized_proposals AS (
  SELECT
    state.id AS state_id,
    seed.proposed_slug,
    seed.proposed_name,
    seed.proposed_market_kind,
    (
      SELECT JSONB_AGG(
        JSONB_BUILD_OBJECT(
          'name', locality.name,
          'slug', locality.slug,
          'country_code', 'US',
          'subdivision_code', seed.state_code,
          'candidate_status', 'needs_review'
        )
        ORDER BY locality.ordinality
      )
      FROM UNNEST(seed.locality_names, seed.locality_slugs)
        WITH ORDINALITY AS locality(name, slug, ordinality)
    ) AS proposed_localities,
    seed.rationale,
    JSONB_BUILD_ARRAY(
      JSONB_BUILD_OBJECT(
        'source', 'docs/market-signals/market-registry-census.md',
        'evidence_kind', 'portfolio_aggregate',
        'observed_on', '2026-09-02',
        'country_code', 'US',
        'subdivision_code', seed.state_code,
        'source_row_count', seed.source_row_count,
        'count_unit', 'pricelabs_syncing_visible_rows',
        'confidence_label', 'high',
        'confidence_score', seed.confidence_score,
        'review_required', TRUE,
        'exception_codes', TO_JSONB(seed.exception_codes),
        'limitations', 'Source rows may include channel duplicates or parent/child inventory and must be reconciled to active Hub listings.'
      )
    ) AS evidence
  FROM proposal_seed seed
  JOIN public.revenue_market_states state
    ON state.country_code = 'US'
   AND state.code = seed.state_code
)
INSERT INTO public.revenue_market_proposals (
  state_id,
  proposed_slug,
  proposed_name,
  proposed_market_kind,
  proposed_localities,
  proposal_source,
  rationale,
  evidence,
  status
)
SELECT
  state_id,
  proposed_slug,
  proposed_name,
  proposed_market_kind,
  proposed_localities,
  'research',
  rationale,
  evidence,
  'needs_review'
FROM normalized_proposals
ON CONFLICT (state_id, proposed_slug)
  WHERE status IN ('draft', 'needs_review', 'approved')
DO NOTHING;
