-- Plain-English (ASD-STE100) version of a client's ask, shown above the
-- original message on /support/[id]. Generated by the Hub through AI Gateway
-- from the redacted client message; one row per ticket, replaced when the
-- message changes (source_hash). Additive: no change to support_tickets, so
-- the ticket guard and updated_at ordering are untouched.

CREATE TABLE support_ticket_ask_plain (
  ticket_id UUID PRIMARY KEY REFERENCES support_tickets(id) ON DELETE CASCADE,
  -- What the client wants to know or wants us to do
  wants TEXT[] NOT NULL CHECK (cardinality(wants) BETWEEN 1 AND 5),
  -- Facts and feelings the client gives as context
  says TEXT[] NOT NULL DEFAULT '{}' CHECK (cardinality(says) <= 5),
  -- stableHash of the client_message it was written from
  source_hash TEXT NOT NULL CHECK (char_length(source_hash) BETWEEN 1 AND 40),
  model TEXT NOT NULL CHECK (char_length(model) BETWEEN 1 AND 120),
  generated_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE support_ticket_ask_plain ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authorized users can view support_ticket_ask_plain"
  ON support_ticket_ask_plain FOR SELECT TO authenticated
  USING (public.has_permission('support', 'view'));
-- Written by the signed-in user whose page view generated it
CREATE POLICY "Authorized users can insert support_ticket_ask_plain"
  ON support_ticket_ask_plain FOR INSERT TO authenticated
  WITH CHECK (public.has_permission('support', 'edit') AND generated_by = auth.uid());
CREATE POLICY "Authorized users can update support_ticket_ask_plain"
  ON support_ticket_ask_plain FOR UPDATE TO authenticated
  USING (public.has_permission('support', 'edit'))
  WITH CHECK (public.has_permission('support', 'edit') AND generated_by = auth.uid());
-- No DELETE policy: rows go with their ticket (ON DELETE CASCADE).
